### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by pandevim** [yashpathack/Supervised-Machine-Learning#1]
@yashpathack hey! nice repo you got here.
But I would like to address one thing. As you're making this well documented repository I'm anticipating to use this as my core source to learn **Machine Learning** in summers. So my suggestion is can you highlight important key words like the equation you used to explain graphs etc.

Keep up the nice work!:smile:

**Comment by yashpathack** [comment]
I'm glad you find this interesting. Sure I'll do that!
